### PR TITLE
Add 2d split unit test

### PR DESCRIPTION
**Pull request by jdinan**
Here's a sketch of the unit test I had in mind for 2d split. It seems to work fine on the `SHMEMX_TEAM_WORLD` cases and crash on the `even_team` cases. It also fails with `npes == 1` for both cases. I had expected this case to work, should it not?

### CODE REVIEW

**Comment by jdinan** [comment]
There were, indeed, some bugs in my unit test. I think they are mostly sorted out now, and hopefully the new PE index calculation makes more sense.

**Comment by davidozog** [comment]
I'm still seeing some errors here... 

@jdinan - It looks like the problem is that `xrange` needs to be greater than `npes`.  I don't think this is clearly specified in the spec though...  When `xrange > npes`, the 2D split doesn't make sense to me...  For example, if `npes` is 1 and `xrange` 2, do you expect just 1 x team?  Or do you expect 2 x teams with the 2nd one equal to `SHMEM_TEAM_INVALID`?

**Comment by jdinan** [comment]
Oh, interesting. What does the spec say about xrange? I think I was expecting that `xrange > npes` would just result in a single xteam that is not full, similar to what happens when `npes % xrange > 0`.

**Comment by davidozog** [comment]
Yeah, it does kinda make sense for the xteam to be "unfilled" in this case, just like some yteams would be unfilled when `npes % xrange > 0`.  My reading/understanding of the spec is that `xrange` is allowed to be (any?) non-negative number, but it's not explicit that the xteam is unfilled when `xrange < npes`.  Is that your interpretation?

For what it's worth, I think it'd be simpler to require that `xrange` be less than or equal to `npes`, but perhaps that's not users' preference.  I'll make a ticket to discuss this on the spec repo.

**Comment by jdinan** [comment]
Given that this is currently allowed, would something simple like `if (xrange > parent->size) xrange = parent->size` at the beginning of 2d split support this case?

**Comment by davidozog** [comment]
~~I think a one-liner like that wouldn't work because it messes with the "size" of the xteam (`xsize` [here](https://github.com/davidozog/sandia-shmem/blob/pr/teams_split_2d-fixes/src/shmem_team.c#L380)).  But I'm sure something relatively simple can be done.  I'll try it out.~~

Ha, nevermind - yeah I think it'll work...

**Review by davidozog — APPROVED** [review]

**Pull request merged**
